### ISSUE TITLE
Add `GlobusApp` method to check login status

### ISSUE THREAD

**Issue by rjmello** [globus/globus-sdk-python#1036]
`GlobusApp` objects currently enable users to manually trigger a login flow via `app.run_login_flow()`, but not to check if a user already has valid tokens (i.e., logged in). I can accomplish this by interacting with the `app._validating_token_storage` object, but that is not a public interface, nor intuitive.

I propose creating an `app.is_logged_in()` method, or similar, which supports a `resource_server` argument. If the user does not specify a resource server, then the method could validate tokens for all associated resource servers.

In addition, we might consider creating an `app.ensure_logged_in()` method, or similar, which would simply run `app.run_login_flow()` if `app.is_logged_in()` returns `False`.

**Comment by derek-globus** [comment]
https://github.com/globus/globus-sdk-python/pull/1041

**Comment by derek-globus** [comment]
pr-1041 resolves this issue.

We'll be releasing SDKv3.45.0 later today which includes this change.
