### ISSUE TITLE
Test suite expansion

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-sdk-python#105]
Conversation topics to get us going:

- [x] what additional nose tests need adding to globus_sdk/tests?
- [x] for testing methods that are actually supposed to call live services, do we want to use real test tokens, or do we want to fake the services, or both?
- [ ] expand to AppVeyor testing for Windows? add OS X on Travis?

**Comment by corpulentcoffee** [comment]
12/1 we discussed possibly registering some test clients of different types and using live refresh tokens.

**Comment by sirosen** [comment]
01/18 we agreed to create a 3-legged oauth app, a native app, a single test user, fetch refresh tokens for each app, and use this as a starting point.

**Comment by bjmc** [comment]
:+1: :100:

**Comment by aaschaer** [comment]
Listing tests for globus_sdk/tests on #127, please let me know if anything is missing.

**Comment by sirosen** [comment]
#131 added AppVeyor.

@corpulentcoffee Do we want to add OSX on Travis? I don't really see the harm in it, so why not, right?

**Comment by corpulentcoffee** [comment]
If it works and is reliable, sure.

**Comment by sirosen** [comment]
> If it works and is reliable, sure.

Nope. It doesn't work. We couldn't even get one OSX build through Travis's enormously overburdened queue for that.

I'm going to close this, as that resolves the question of whether or not to add OSX via Travis.

**Comment by corpulentcoffee** [comment]
Yes, the basis of my comment was hearing Jason mention that it was slow/unreliable.
