### ISSUE TITLE
Question: Handling identity expiration in HPC environment

### ISSUE THREAD

**Issue by csparker247** [globus/globus-sdk-python#1053]
I use the Globus SDK in a SLURM-based HPC environment where jobs are queued and run at a later time according to some scheduling algorithm. My workflow is usually something like `stage data → long processing job → backup data`, where the staging and backup is handled by Globus. Depending on the size of the queue when I submit these workflows, there can be a large delay between submission and execution, particularly for the backup job which is dependent on the processing in the middle.

After submission, I have no way of interacting with these queued jobs, so when I submit my workflow, I prompt for a Globus login and make sure that I have a valid token. Occasionally, though, the backup jobs fail for one of two reasons:

1. The initial token has expired such that getting a refresh token fails. Honestly, this might have been a bug in my original authentication code, and I've since switched to using the `UserApp` class (as discussed in #1050), so this might not be an issue anymore.
2. My identity provider requires me to login with SSO periodically every few days, so my job connects to Globus but fails because my endpoint is unavailable.

I'm wondering if there are good suggestions for me to detect and handle these likely failure conditions _at job submission time_ rather than crossing my fingers and hoping. For example, does the globus-sdk provide a public way to get the token expiration time so I can force a refresh if the token will expire in the next 24 hours? Similarly, is there some way to make sure my login with the endpoint's identity provider isn't about to expire? 

These are just some ideas. If there are other ways of mitigating these sorts of things, I would love to know!

**Comment by derek-globus** [comment]
Hey Seth, point (1) should be addressed by your referenced use of UserApp + refresh tokens.

Globus Auth access tokens expire 2 days after issuance. Refresh tokens on the other hand expire 6 months after the last recorded usage. Access tokens are used to make service requests whereas refresh tokens are used to request new access tokens without a user driven login flow.

There is a public interface to retrieve the expiration timestamp for a stored access token but once we get issue #1050 ironed out (in the next day or two), that will hopefully resolve any need to be concerned with evaluating token expiration times.

**Comment by csparker247** [comment]
> Hey Seth, point (1) should be addressed by your referenced use of UserApp + refresh tokens.
> 
> Globus Auth access tokens expire 2 days after issuance. Refresh tokens on the other hand expire 6 months after the last recorded usage. Access tokens are used to make service requests whereas refresh tokens are used to request new access tokens without a user driven login flow.

Excellent, that all sounds good and like something I suspected was true.

**Comment by derek-globus** [comment]
Point (2) has a less clear answer unfortunately. 

Just to make sure I understand the drive here, is this a good summary of your use case?
You're initiating a long running process and can only drive a user login at the very start. You'd like to inspect the current authentication state against a particular OIDC whose authentication timeout is known to be configured on a particular collection. This is in service of ensuring that a sufficiently large time buffer exists between the last authentication time and the collection's authentication timeout and therefore that the job is unlikely to fail due to authentication timeouts.

I've been working with our Auth team and it's unclear whether there is actually a path to do this using the apis which exist today.

As I continue to discuss with the team, have you looked into using our [Flows](https://www.globus.org/platform/services/flows) and [Compute](https://www.globus.org/compute) services at all? Compute is a service to execute code in your own environment (particularly a HPC). Flows is a service to define and run reusable cloud-hosted execution DAGs. You could model the above steps using a flow whose definition looked like `[Run Transfer (stage data)] -> [Run Compute Job (long processing job)] -> [Run Transfer (backup data)]`. Flows will handle an authentication required errors in each step by pausing and emailing whoever initiated the flow run to re-authenticate and resume.
Not exactly what you were asking for but should at least provide an immediately more sane authentication story.

**Comment by csparker247** [comment]
> Just to make sure I understand the drive here, is this a good summary of your use case?
> You're initiating a long running process and can only drive a user login at the very start. You'd like to inspect the current authentication state against a particular OIDC whose authentication timeout is known to be configured on a particular collection. This is in service of ensuring that a sufficiently large time buffer exists between the last authentication time and the collection's authentication timeout and therefore that the job is unlikely to fail due to authentication timeouts.

Yes, this is exactly it. I don't necessarily need a programmatic way to do the reauth for an OIDC. It is sufficient for my purposes to warn the user that they need to go to the web interface and re-up the auth. 

> As I continue to discuss with the team, have you looked into using our [Flows](https://www.globus.org/platform/services/flows) and [Compute](https://www.globus.org/compute) services at all? Compute is a service to execute code in your own environment (particularly a HPC). Flows is a service to define and run reusable cloud-hosted execution DAGs. You could model the above steps using a flow whose definition looked like `[Run Transfer (stage data)] -> [Run Compute Job (long processing job)] -> [Run Transfer (backup data)]`. Flows will handle an authentication required errors in each step by pausing and emailing whoever initiated the flow run to re-authenticate and resume.

Yes, I think I see how both Flows and Compute could accomplish what I need. Compute maps most directly onto what I'm already doing. In either case, though, it seems like I would need some sort of persistent or long-running service running on my HPC resources to be useful,  unfortunately I don't have the admin access required for that.

**Comment by csparker247** [comment]
> In either case, though, it seems like I would need some sort of persistent or long-running service running on my HPC resources to be useful, and unfortunately I don't have the admin access required for that.

To clarify this point somewhat, with Flows, it seems I would need a persistent action provider HTTP service running in my HPC environment that would pick up and execute the `Run compute job` stage with my scheduling system (Slurm). That would require both the ability to spin up a persistent service (available after I log out) and maybe some ability to open the firewall for communication with the service?

Similarly with Compute, I would need a persistent compute endpoint that could interface Slurm. While I see that there are example configurations for this in the Compute documentation, this only makes sense to me if the system admins set up a multi-user endpoint. I don't understand how a single-user endpoint would persist after I logout of the HPC, but maybe there's something I'm missing there.

**Comment by derek-globus** [comment]
This is the overall structure I was suggesting.

![transfer-compute-transfer-flow](https://github.com/user-attachments/assets/846c66c2-3845-4f7c-95dc-c442af9ee239)

---

As you point out, it would require running a persistent compute endpoint on the HPC's head node. This endpoint however doesn't need to receive inbound traffic. In Flows, compute tasks are submitted using our existing compute action provider ([docs](https://globus-compute.readthedocs.io/en/latest/actionprovider.html)). This would add the task to a queue which your HPC-hosted endpoint reads from/writes to.

>  I don't understand how a single-user endpoint would persist after I logout of the HPC without admin access to install a systemd service, but maybe there's something I'm missing there.

From a discussion with our team who runs the compute service, it sounds like non-privileged users starting detached processes which persist after they disconnect (screen, tmux, etc.) is a pretty common practice across clusters. If this is something that your cluster's admins don't allow however that would make make this whole process much more complex (if not impossible).

**Comment by csparker247** [comment]
> This is the overall structure I was suggesting.

This is an interesting diagram. I had been thinking of Flows and Compute in separate terms, but I see now what you mean. If I can get it set up in my environment, this would accomplish my goals.

> From a discussion with our team who runs the compute service, it sounds like non-privileged users starting detached processes which persist after they disconnect (screen, tmux, etc.) is a pretty common practice across clusters. If this is something that your cluster's admins don't allow however that would make make this whole process much more complex (if not impossible).

This is the somewhat tricky part. I can and have left `screen` running on the cluster login nodes to monitor job logs, but that's never been on any significant timescale. My understanding is that our admins frown upon tying up the login nodes with long-running processes (with good reason), so it's unclear to me how long I might be able to run a Compute endpoint before they would shut it down. I suppose there's one good way to find out!

Thank you, this has been very helpful. I do still think that some sort of SDK-based way of querying the identity provider status might be useful, but for the question at hand, I think I have some things to work from. Thanks!

**Comment by csparker247** [comment]
>     2. My identity provider requires me to login with SSO periodically every few days, so my job connects to Globus but fails because my endpoint is unavailable.

Quick follow-up for completeness. I spoke with my Globus admin about this problem yesterday, and he said that this was an issue with an older version of the Globus server that we were running, and that it should be fixed now. So it sounds like this isn't even an issue anymore!
