### ISSUE TITLE
Add support for OIDC compliant userinfo call to Globus Auth

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#106]
This is blocked waiting on the addition of the userinfo endpoint, but it's coming soon.

When it does, we should presumably be adding SDK support.

**Comment by bjmc** [comment]
Userinfo endpoints are now available at `<host>/v2/oauth2/userinfo`

**Comment by sirosen** [comment]
As a reminder for myself: [docs here](https://docs.globus.org/api/auth/reference/#get_or_post_v2_oauth2_userinfo_resource)

Since the response type is so simple, there's no need for a custom response class.
Let's plan this for the next version of the SDK.
