### ISSUE TITLE
Clarify difference between submission_id and task_id in the docs

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-sdk-python#115]
The [get_submission_id documentation](http://globus.github.io/globus-sdk-python/clients/transfer.html#globus_sdk.TransferClient.get_submission_id) should at least include the same caveat as the rest API "*Note that this is different than the task id returned by the submit operations*" if not an explanation of how its purpose differs from that of a task_id

**Comment by jaswilli** [comment]
I'm not sure we need to or want to be re-documenting the Transfer API in the SDK docs. If an SDK user is going to make a call to `get_submission_id()` they would presumably know why they're doing it already.

At most I'd say perhaps we could link to the external API docs like we do in some other cases.

**Comment by corpulentcoffee** [comment]
> If an SDK user is going to make a call to `get_submission_id()` they would presumably know why they're doing it already. [...] At most I'd say perhaps we could link to the external API docs like we do in some other cases.

I can add a blurb to that effect.
