### ISSUE TITLE
Implement Client Credentials Authorizer

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#123]
I was working on an example of the Client Credentials grant when I realized that this is a possibility.

The `RefreshTokenAuthorizer` tracks expiration time and automatically requests new tokens for the user.
However, there are no automated utilities for managing tokens fetched via Client Credentials grants.

It occurred to me that we could define a `ClientCredentialsAuthorizer` built from a `ConfidentialAppAuthClient` and a set of scopes.
The scopes are necessary in order to specify what resource server (and scopes against it) are used -- the authorizer can fetch and store access tokens via the client credentials grant, always choosing the top-level token.
We could even have it error-out if `other_tokens` are returned (i.e. bad scopes supplied).

Does this have value? Would it help client authors?

**Comment by stumartin** [comment]
Decide this is a "nice to have" for 1.0

**Comment by aaschaer** [comment]
closed by #164
