### ISSUE TITLE
change AuthClient errors from ValueErrors to ?

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-sdk-python#139]
The ValueErrors thrown by AuthClient's oauth2_get_authorize_url() and oauth2_exchange_code_for_tokens() when called out of order should probably be some kind of GlobusError?

**Comment by sirosen** [comment]
Just scanning old issues, I had a thought:
`GlobusUsageError` inheriting from `GlobusError` and `ValueError`.

Won't break any sane client code, good for the indefinite future.
