### ISSUE TITLE
TransferData and deadline property

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-sdk-python#142]
The Transfer API accepts `deadline` (format `2017-02-24 15:44:46.618026+00:00`) as a part of both the submit and delete task requests. It's not documented in the Transfer API docs.

Should we a) get it documented and/or b) add it as a named argument to the `TransferData` and `DeleteData` classes so it's documented and easily usable in the SDK?

**Comment by sirosen** [comment]
Both (a) and (b) are necessary, but independent.

It's always _preferable_, but not necessary, to start with the addition of documentation for the API, as it lets the API maintainers set the expectation on things like date format. That protects us from making mistakes in the SDK docs.

For example, does the API and, by proxy, the SDK accept all of ISO 8601 for `deadline`? Yeah, as Globus team members we can read the API ourselves, but we shouldn't, in principle, have to be conversant in various API codebases.

I'll open an issue to get the ball rolling on (a) and we can add it directly in the SDK if that takes a long time for some reason.
