### ISSUE TITLE
Missing tests and their requirements

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-sdk-python#151]
The following are SDK tests that are missing due to missing/infeasible requirements.

Myproxy activation. Requires a stable endpoint with a myproxy login for SDK Tester. (may be depreciated at some point anyways)

Login-flow. Requires automating a browser and SDK Tester's login credentials being made public.

Code exchange. Requires login-flow or a non expiring test code.

Live openid JWT decoding. Requires login-flow, a non expiring id_token, or an auth resource other than code exchange that responds with an an id_token.

Dependent token grants. Requires a resource server client and scopes to be set up.

Managed endpoint resources. Requires SDK Tester to have privileges on a managed endpoint, which would give public access to privileges on a managed endpoint.

**Comment by sirosen** [comment]
I'm going to copy this content, converted to a checkbox list, into #322 to consolidate.
