### ISSUE TITLE
pypy3 test failure

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-sdk-python#157]
https://travis-ci.org/globus/globus-sdk-python/jobs/209163244

Not sure what's changed to cause the failure but it's started failing on recent PR builds.

**Comment by bjmc** [comment]
FWIW, you [may want to stick to ASCII]( http://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication) and stay away from utf-8 for HTTP headers.
