### ISSUE TITLE
Implement pattern/filter support in add_item(s) transfer function

### ISSUE THREAD

**Issue by kevinkrieger** [globus/globus-sdk-python#165]
Currently (based off the documentation) it appears that the add_item() function only allows you to add a single item to either transfer or delete at one time via the "/source/path/dir/", "/dest/path/dir/" arguments (and also to recursively transfer files).
In my application, It would be very handy to be able to use a pattern or filter in order to add all items that match the pattern or filter. The behaviour I'm looking for would essentially replace the following code with just one add_item call with the pattern, and then the transfer (would still need to generate my pattern):

```
listing_pattern = "name:~*{}*rawacf.bz2".format(self.sync_radar) # You absolutely need the '~' for this pattern to work. Not obvious from docs
listing = self.transfer_client.operation_ls(source_uuid,path=listing_path,filter=listing_pattern)
files_to_sync = [entry['name'] for entry in listing]
transfer_data = globus_sdk.TransferData(self.transfer_client, source_uuid, dest_uuid, label=inspect.currentframe().f_code.co_name,sync_level="checksum")
source_dir_prefix = "/chroot/sddata/raw/{}/{}/".format(self.sync_year,self.sync_month)
dest_dir_prefix = self.sync_local_dir
for file in files_to_sync:
    transfer_data.add_item("{}/{}".format(source_dir_prefix,file),"{}/{}".format(dest_dir_prefix,file))
transfer_result = self.transfer_client.submit_transfer(transfer_data)
return transfer_result
```

**Comment by sirosen** [comment]
I don't think this is a good idea, and in direct discussions with other maintainers they have agreed, for a couple of reasons.

To explain our thinking a little bit
- The API doesn't have underlying support for this
  This has a couple of implications, among them that we'd be breaking the 1-to-1 mapping between methods and API calls that we try to maintain.
- It will be hard to maintain long-term and for all supported platforms/endpoint types
  One of our biggest concerns is maintenance burden. We understand and respect the desire for more features, but we need to weigh that against the difficulty of testing and maintaining those features.
- You can already implement it yourself
  The fact that you've been able to produce this code sample is already a huge step forward (from the Dark Times before the SDK), and it's not too much more work for you to wrap this up in a helper function of your own design. That protects against our maintenance concerns, and can be tailored to your specific needs.

If we had a `globus-contrib` space, as some projects do, I'd suggest that you submit this there, but we aren't sure there's enough interest to merit one.

I hate to say it, but I'm closing this as a wontfix.

**Comment by kevinkrieger** [comment]
Thanks for the response - I figured it was a long-shot but wanted to see anyways.
As you say it can be implemented with ls so I'm not too worried.

**Comment by sirosen** [comment]
Sure! We're happy to have folks using it, and especially happy to hear what people want.

Please, if there are other things you'd like us to improve, continue to let us know. :+1:
