### ISSUE TITLE
Setup an install extra for getting `python-jose`, i.e. `globus_sdk[jwt]` or similar

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#168]
It's kind of lame to ask people to enable optional features by explicitly installing `python-jose`.
The cool thing to do with setuptools is to declare an extra. For example, you could ask for a version + extras like so:
```shell
$ pip install 'globus_sdk[jwt]==0.7.1'
```

Setuptools [supports this](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) with minimal effort. The only big question I have is how we go about testing the results.

@jaswilli, @corpulentcoffee Are there other concerns we might have about adding this as an extra? Is there a better name than `jwt` for the `python-jose` extra?

If we do this, updates to the `GlobusOptionalDependencyError` messaging should probably be applied.

**Comment by corpulentcoffee** [comment]
Closed by #169
