### ISSUE TITLE
Add support for Globus Auth userinfo endpoint

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#202]
Needed for globus/globus-cli#115

**Comment by mattias-lidman** [comment]
Docs for the new `urn:globus:auth:scope:auth.globus.org:view_identity_set` scope is not yet up on docs.globus.org, but are available in the top-level comment [here](https://github.com/globusonline/globus-auth/pull/931).

**Comment by sirosen** [comment]
So, it seems that this may have been closed out by #114 ?
Need to take a moment and review. This might be okay to close.

**Comment by sirosen** [comment]
This was, indeed, done by #114 , but it would be nice to update docs to capture what the needed scopes are.
