### ISSUE TITLE
PaginatedResource's interator/generator

### ISSUE THREAD

**Issue by lukaszlacinski** [globus/globus-sdk-python#213]
PaginatedResource's iterator does not seem to be implemented correctly. When I run

tasks = tc.endpoint_manager_task_list()
print(tasks)
print(tasks)

the second print() gets an empty list:

PaginatedResource([GlobusResponse({'type': 'DELETE', 'source_endpoint_id': 'd0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'source_host_path': '/~/shared/', 'task_id': '5b235fc2-3f0a-11e7-bd15-22000b9a448b', 'destination_endpoint': None, 'source_endpoint': 'lukasz#d0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'owner_string': '4e6db83a-c767-4e53-ac96-d89b2cbe6577@clients.auth.globus.org'}), GlobusResponse({'type': 'TRANSFER', 'source_endpoint_id': 'd0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'source_host_path': '/~/shared/', 'task_id': '2c1ff326-3f09-11e7-bd15-22000b9a448b', 'destination_endpoint': 'go#ep1', 'source_endpoint': 'lukasz#d0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'owner_string': 'lukasz@globusid.org'}), GlobusResponse({'type': 'TRANSFER', 'source_endpoint_id': 'ddb59aef-6d04-11e5-ba46-22000b92c6ec', 'source_host_path': None, 'task_id': '181c9945-3f09-11e7-bd15-22000b9a448b', 'destination_endpoint': 'lukasz#d0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'source_endpoint': 'go#ep1', 'owner_string': 'lukasz@globusid.org'}), GlobusResponse({'type': 'DELETE', 'source_endpoint_id': 'd0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'source_host_path': '/~/shared/', 'task_id': '1834c07e-3f06-11e7-bd15-22000b9a448b', 'destination_endpoint': None, 'source_endpoint': 'lukasz#d0c79c14-3c5f-11e7-bcfe-22000b9a448b', 'owner_string': '4e6db83a-c767-4e53-ac96-d89b2cbe6577@clients.auth.globus.org'})])
PaginatedResource([])

**Comment by jaswilli** [comment]
I think you're exhausting the iterator in your first `print()`, which is basically doing a `list(tasks)` before printing the output.

Does:
```
for task in tasks:
    print(task)
```

Work?

**Comment by lukaszlacinski** [comment]
It works only once (one for statement). If I want to iterate again through all tasks it does not print anything because the iterator got stuck at StopIteration in the first 'for' statement. I assume that every time I do list(tasks) should get the same list.

**Comment by jaswilli** [comment]
That's just how iterators work in Python. You can only go through once and then it will start raising `StopIteration`.

If you know you're going to want to use the `PaginatedResource` more than once you can turn it into a list, which _is_ iterable multiple times--just be careful if you're going to do it on a large set of tasks because it will go and fetch them all.

Example:
```
tasks = list(tc.endpoint_manager_task_list())

for task in tasks:
    print('doing something with `tasks`')

for tasks in tasks:
    print('doing more stuff with `tasks`)
```

**Comment by bjmc** [comment]
@lukaszlacinski Unfortunately that somewhat un-intuitive behavior is the standard for a Python iterator.

If you need to iterate multiple times, you'll have to hold onto all the items in a list (or tuple or other data structure)

```python
task_list = list(tasks)
all(task_list)
any(task_list
```

**Comment by lukaszlacinski** [comment]
Ouch! I misunderstood an idea of PaginatedResource.
