### ISSUE TITLE
How should we improve PaginatedResource documentation to clarify that second iteration is empty? Are new/additional behaviors desirable or required?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#215]
In various forms, we've seen confusion over the fact that a PaginatedResource does not record the results of paging and yields the results as it gets them.
Usually, this is manifest in the form of someone trying to walk a PaginatedResource multiple times, and being surprised that the second iteration is empty.

So, first and foremost:
How do we make this clearer in the docs?

Secondly, which, if any, of the following behaviors would help resolve the issue?
1. Have paginated calls accept `store_results=True`, enabling the use of a list to record the results as they are iterated
2. Add a method, `PaginatedResource.reset()` which restarts paging, and which can document that it's discouraged but useful for fetching fresh results
3. On repeat iterations (i.e. after the first `StopIteration`), have `PaginatedResource` _raise an error_ which explains how to do multiple iterations correctly (either listify, or make a fresh call)
4. On repeat iterations, have `PaginatedResource` restart paging, even though it's inefficient (optionally log a warning)

EDIT: updated to numbered list to make things easier to discuss.

**Comment by aaschaer** [comment]
We should probably make it clear in the docs that PaginatedResources are designed to make several lazy network calls and handle potentially very large amounts of response data, and thus don't record their results. Putting it in a NOTE: might get people's attention.

However, I feel like many users don't read the docs until they run into a problem, so I am very in favor of option 3. We should at the very least let people know they are doing something wrong if they are looking for more results at the end of a PaginatedResource.

Adding options 1 and/or 2 would be nice, but might be misused. Would need notes about proper usage.
If we do both, calling reset with `store_results=True` should raise an error.

Not a huge fan of 4, would rather make the user call `reset()` than make it easy for them to use inefficient behavior, lest we get complaints about the "SDK being slow" or something.

**Comment by sirosen** [comment]
I agree that (4) is probably just bad. I included it for completeness, but prefer `reset()` being explicit if allowed.

I wouldn't allow both (1) and (2), I think. They're slightly different notions of what repeat iteration means -- getting cached results vs. an updated/new set of results.
Combining them seems like it raises some issues. For example, if you wanted to `reset()` after the initial call stored results, maybe you should be allowed, and that "clears the cache"? I'm not sure we want to open up those problems.

> However, I feel like many users don't read the docs until they run into a problem, so I am very in favor of option 3. We should at the very least let people know they are doing something wrong if they are looking for more results at the end of a PaginatedResource.

Glad to hear it! I also am most in favor of making it an error to iterate multiple times, as it gives us a good place for messaging.
Adding a `NOTE` in the docs is probably good too, though I agree that most people wouldn't read it.

@corpulentcoffee, @jaswilli, I'm curious about your thoughts on (3) in particular. Does this seem reasonable?

**Comment by bjmc** [comment]
Adding `store_results=True` and an internal caching system seems overkill to me. Callers can easily use `list()` to store the results themselves, and that's more obvious.

**Comment by jaswilli** [comment]
Explicitly calling out the behavior in the docs seems like the only reasonable approach. Re-raising `StopIteration` with a helpful message shouldn't really be necessary but it's a nice touch, so why not.

**Comment by sirosen** [comment]
> Re-raising `StopIteration` with a helpful message shouldn't really be necessary but it's a nice touch, so why not.

To clarify, I meant that we could raise a `GlobusUsageError`. So, code that iterates twice won't be silent on the second iteration, it will actually fail under that approach.

The main disadvantage, I think, is the obvious non-idiomatic nature of that behavior. The advantage is that the failure is no longer silent, so developers are likely to see the message.

I don't think putting a message on the `StopIteration` gains us much of anything -- no one would read it, right?

**Comment by jaswilli** [comment]
> To clarify, I meant that we could raise a GlobusUsageError. So, code that iterates twice won't be silent on the second iteration, it will actually fail under that approach.

Ah. I'm less enthused about that change then. It seems like just asking for trouble by changing the way the language behaves by default and I'd be worried about random failures downstream as fallout.

Unless of course there's a good example out there of someone doing something like this with good results.

**Comment by bjmc** [comment]
Raising a different exception [seems nonstandard](https://stackoverflow.com/questions/39622288/why-exhausted-generators-raise-stopiteration-more-than-once):

> Once an iterator’s __next__() method raises StopIteration, it must continue to do so on subsequent calls. Implementations that do not obey this property are deemed broken.

Maybe just calling this out loudly in the docs is the best approach.

**Comment by sirosen** [comment]
I wasn't aware that the behavior was a strict spec requirement.
I guess that nixes option (3). And I grant that it's a weird idea, but it's at the time of iteration that we'll see end-user confusion.

So, we can add a note to the docs to call this out explicitly, and I agree with @bjmc that having a caching system builtin is much less obvious than `list(PaginatedResource)`.

I guess that leaves, as the only candidate feature, `PaginatedResource.reset()`. Its docs would also be a reasonable place to call out that this is potentially inefficient for certain use cases, and should only be used if you actually want a fresh set of results.

**Comment by jaswilli** [comment]
I think less is more in this case. Let's put a blurb in the docs about `PaginatedResource` being an iterator, only being able to step through it once, and mention the option of `list()`ing it with the caveat that it may be an expensive operation.
