### ISSUE TITLE
Symlink Support

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-sdk-python#216]
Here is my proposal for how we should add Transfer's upcoming support of symlinks to the SDK:

**Task submission:**

Add `recursive_symlink="ignore"` to `TransferData.__init__`'s named arguments, then add it as one of the `TransferData`'s query paramaters.

SDK will not enforce that the value is in "ignore", "keep", or "copy" to stay in our model of giving back the errors Transfer gives us.

Add `add_symlink_item(self, source_path, destination_path)` to `transferData`'s methods, akin to `TransferDat.add_item` that adds a `transfer_symlink_item` to the DATA field of the submission data.

(could also add `symlink=False` to the existing `add_item` method, but a seperate method avoids the issue of `recursive` and `symlink` both being True.)

No code changes to `DeleteData` `TransferClient.submit_transfer` or `TransferClientsubmit_delete` should be needed.

**Task Monitoring:**

No code changes should be needed for task monitoring as we just return a `TransferResponse` that will now happen to have a few more data fields.

**Symink Creation:**

add an `operation_symlink(self, endpoint_id, symlink_target, path, **params)` method to `TransferClient`.

That makes a POST request to /operation/endpoint/<endpoint_id>/symlink with the given request parameters and returns a `TransferResponse`.

**Comment by sirosen** [comment]
> SDK will not enforce that the value is in "ignore", "keep", or "copy" to stay in our model of giving back the errors Transfer gives us.

I like this direction, and find it consistent with the choice for `sync_level`.

---

This all seems correct/right. As soon as Transfer releases symlink support, I'd say we can add this.
