### ISSUE TITLE
Missing Transfer API Helpers (other than management console)

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#22]
Kyle mentioned to me that shared endpoint creation is missing.

Adding that is easy, but we should try to do make sure there are no other misses.
Trying to build a list just now, this is what I came up with.
- [x] Create Shared Endpoint
- [x] Get Task pause info
- [ ] Get effective endpoint pause rules

Although the pause related ones are tied to the management console, they're out in other parts of the API, so I think we should add them.

EDIT: removed the ones where I was mistaken.

**Comment by bd4** [comment]
Endpoint activation already exists. Get endpoint server by id is important, the others not so much.

**Comment by bd4** [comment]
Looks like get ep server by id already exists too. The others are pretty low priority I think.

**Comment by sirosen** [comment]
Closing in light of #88 and similar issues. Since it doesn't look like we're going to work through complete coverage in the near term, we should just track one-by-one.
