### ISSUE TITLE
Make testsuite more robust to ConnectionErrors

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#221]
When we run the testsuite on Travis and AppVeyor, the build matrix is a decent size, and the total number of tests run starts to reach into the 1K order of magnitude.
Very often, with this many tests running, we'll see at least one ConnectionError, but it's just a bit of network flap.

To make the testsuite more robust, we just need to do some retries, and a potentially easy way is to clean and restart tests that hit connection errors. In any case, we need to handle these conditions a bit better than we currently do.

**Comment by jaswilli** [comment]
Closed by #234
