### ISSUE TITLE
Look into making globus-sdk[jwt] non-optional

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#235]
Specifically, now that we're using `pyjwt` and (therefore) `cryptography`, we should consider making that dependency a normal requirement.
`globus-sdk[jwt]` would continue to exist as an empty extra for compatibility.

One of our key questions is whether or not we can trust AppVeyor testing to validate that Windows installs work. What version of Windows does AppVeyor run? If we can't trust it, how will we test for Windows? (If we can't trust it, doesn't that undermine all of our testing on that platform anyway?)

**Comment by jaswilli** [comment]
#252

**Comment by sirosen** [comment]
Yeah. I created a branch which installs `globus-sdk[jwt]` on appveyor. We can check on the testing there, decide on what we need to do in order to be comfortable here...

**Comment by sirosen** [comment]
It looks like there might be issues with cryptography + windows + Python 3.4:
https://ci.appveyor.com/project/globus/globus-sdk-python/build/1.0.266/job/hg8ura11mg2ocxfs

_sigh_ I don't know what to do with this information.

**Comment by sirosen** [comment]
Okay, Py3.3 has been EOLed as of a couple of months ago: https://www.python.org/downloads/release/python-337/

@jaswilli, should we maybe drop _official_ Py3.3 support, make `[jwt]` included by default, and close the books on this until someone comes back to us with an issue?

A more sophisticated option: because we only ship source distributions, we can have setuptools dispatch in its behavior based on the environment. We could keep the dependency optional, have it installed by default, and then add a var like `GLOBUS_SDK_SETUP_SKIP_JWT=1`. We'd keep all of our skippable tests and skip the install of pyjwt in our test matrix for at least one tested version.
`pip` and `setuptools` also let us dispatch on platform, so we could check for Windows + Py3.3 explicitly (but what if it breaks on 3.7 or starts breaking on 2.7 or 3.4 or... There are so many ways for it to go wrong.

**Comment by jaswilli** [comment]
I suspect the "Using Windows and cannot use any version of Python 3 but 3.3" demographic is incredibly small. I'm fine with either dropping 3.3 support altogether or leaving 3.3 on Windows broken.

**Comment by jaswilli** [comment]
Closed by #257
