### ISSUE TITLE
Globus App Portal Should Allow Renaming

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#248]
This is a small detail, but it would be good if Project were allowed to be renamed:

![image](https://user-images.githubusercontent.com/814322/33104124-5d48934c-cedb-11e7-8068-964545d2ed19.png)

I was able to delete the project and create a new one, so it's not a huge issue, more of a UI / interaction thing :)

**Comment by bjmc** [comment]
Thanks, @vsoch!

I've marked this as a feature request. It's certainly a good suggestion and I'll bring it up for prioritization.

**Comment by jaswilli** [comment]
Hi @vsoch,

Since there's nothing to be done with the SDK itself I'm going to close this issue but it sounds like the change is being worked on internally.

Thanks for the feedback and for being a Globus developer!

**Comment by vsoch** [comment]
Thank you! :D
