### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#249]
I'm having some trouble with the OAuth flow in the example provided here http://globus-sdk-python.readthedocs.io/en/latest/tutorial/#step-3-get-some-access-tokens:

```
Sorry, but we encountered a problem while servicing your request.

Occurred at time:
2017-11-22T00:58:16.026509+00:00
Error ID:
38ff8f82-cf20-11e7-98d9-0e2bdca94fb4
Error code:
UNEXPECTED_ERROR
```

I've verified that I'm using the access token granted to me, and am not sure what else to look into. Any help or debugging advice would be appreciated!

**Comment by bjmc** [comment]
What stage of the process are you seeing that error on? What scope(s) is your client requesting?

I checked our logs and found the following:

> [ERROR] globus.auth.error.views <<38ff8f82-cf20-11e7-98d9-0e2bdca94fb4>> 'ascii' codec can't encode character u'\u201d' in position 142: ordinal not in range(128)

That character is a curly/smart quote, `”`. Is it possible it snuck in from a copy-paste somewhere?

Obviously we need better error-handling for invalid characters, but if you can figure out where that curly-quote is coming from and remove it or replace with a normal quote `"`, I hope that will get you back in business for right now.

**Comment by vsoch** [comment]
The only thing I copy pasted was my original client id (no quotes there) and then the url that was produced by the function:

```
CLIENT_ID
'ae32247c-2c17-4c43-92b5-ba7fe9957dbb'

print('Please go to this URL and login: {0}'.format(client.oauth2_get_authorize_url()))
Please go to this URL and login: https://auth.globus.org/v2/oauth2/authorize?code_challenge_method=S256&code_challenge=DZK_iNytU3wMprSiR3uytyfRHSnuJASODl0dxqLkfa4&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=openid+profile+email+urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall&response_type=code&state=_default&client_id=ae32247c-2c17-4c43-92b5-ba7fe9957dbb&access_type=online
```

I just went through the flow and I didn't find any setting of variables that had any kind of quote, so I went back and looked at my App settings. I did have a quote (that was copy pasted from somewhere) in the App name, so i replaced it. Does your API parse the name on the back end? I think it just worked for the first time!

**Comment by bjmc** [comment]
@vsoch Sorry about the inconvenience!

We're not explicitly parsing the app name, but there are places where we log the app name and it looks like Python 2 `string.__repr__` is throwing an error on non-ASCII characters. Upgrading to Py3 is on the long-term agenda, but in the meantime we'll have to be more careful with our `__repr__`s and log entries.

I'm going to close this issue and open an internal ticket for our backend.

Thanks for the report!

**Comment by vsoch** [comment]
Thanks for the help!
