### ISSUE TITLE
decoding jwt requires cryptography

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#252]
The `id_token` that can be decoded with jwt is great for getting user info without needing to do a second call to user info, but when doing the decode it is missing an algorithm:

```
jwk_as_pem = jwt.algorithms.RSAAlgorithm.from_jwk(
uwsgi_1   | AttributeError: module 'jwt.algorithms' has no attribute 'RSAAlgorithm'
``` 

I was able to fix this by installing cryptography. Should this be a dependency for the globus-sdk-python application or third parties that use it?

**Comment by vsoch** [comment]
Oh and there is no huge issue / anything blocking what I'm working on, I've added the dependency to my application, but wanted to discuss which strategy made most sense. Thank you!

**Comment by bjmc** [comment]
The `jwt` features are [listed as a optional dependency](https://github.com/globus/globus-sdk-python/blob/master/setup.py#L32), because some people might want to use the SDK without them (particularly if they're in an environment where `cryptography` is difficult to build)

If you install the SDK using `pip install globus-sdk[jwt]` it should pull in `cryptography` for you as a dependency automatically.

Maybe we need to do a better job of highlighting this in the documentation.

**Comment by bjmc** [comment]
Also, thanks for your report! It's great getting feedback from developers on ways we can improve and make things easier.

**Comment by vsoch** [comment]
Oh fantastic! I'll use the `[jwt]` module addin instead of installing crytography separately. And +1 to tweaking the docs. They are really well written/detailed, and a few helper "entrypoints" might lead to the right place.

**Comment by jaswilli** [comment]
Hi @vsoch,

Also, the SDK provides a convenience method for handling the the `id_token` so you don't need to mess with the JWT library directly.

Once you have the `cryptography` dependency installed (as discussed, `globus_sdk[jwt]`) you can call the `decode_id_token` function against a token response and get the contents of the `id_token`, e.g.:

```python
import globus_sdk

# ... set up and make a token request that includes an id_token

id_token = token_response.decode_id_token(globus_sdk.AuthClient())
```

[Link to the docs](http://globus-sdk-python.readthedocs.io/en/stable/optional_dependencies/#oidc-id-tokens)

**Comment by vsoch** [comment]
Thanks! Yeah that one I figured out, very useful!

https://github.com/singularityhub/sregistry/blob/add/globus/shub/plugins/globus/utils.py#L89
