### ISSUE TITLE
Endpoint discoverability

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#253]
heyo! I have a simple singularity image registry running with it's storage as a personal endpoint, and the flow I'm implementing is the following:

1. user associates with globus
2. a save / transfer button appears by a collection or container. The user can push it to transfer an image provided by the registry endpoint to his/her chosen endpoint.

It's relatively easy to follow the example and get the list of user's endpoints:

```
client.endpoint_search(filter_scope="my-endpoints")
[instance:139640414517624] TransferClient.endpoint_manager_monitored_endpoints({'filter_scope': 'my-endpoints'})
Creating PaginatedResource(0) on TransferClient(instance:139640414517624):get:endpoint_search
PaginatedResource should have more results, requesting them now
[instance:139640414517624] GET to endpoint_search with params {'offset': 0, 'limit': 25, 'filter_scope': 'my-endpoints'}
[instance:139640414517624] request will have authorization of type <class 'globus_sdk.authorizers.access_token.AccessTokenAuthorizer'>
Setting AccessToken Authorization Header: "Bearer ...lQgbc" (last 5 chars)
[instance:139640414517624] request will hit URL:https://transfer.api.globus.org/v0.10/endpoint_search
[instance:139640414517624] Request made to URL: https://transfer.api.globus.org/v0.10/endpoint_search?offset=0&limit=25&filter_scope=my-endpoints
[instance:139640414517624] request completed with response code: 200
```
what I'm interested in is how to discover endpoints. The simplest case is finding the endpoints that are servers (e.g., for my account an example would be SRCC sherlock) but the more complicated use case is "find me all the endpoints that I have priviledges to work with"

I did the whole "autocomplete to discover the right function" deal, but there are quite a few! :)

![image](https://user-images.githubusercontent.com/814322/33529871-69d5d292-d82b-11e7-97b9-892c0d74dfcf.png)

And even for ones that seem intuitive, it expects a filter like "my-endpoints."

```
client.endpoint_search()
globus_sdk.exc.TransferAPIError: (400, 'BadRequest', "scope 'all' requires an additional filter parameter", '6VPyGAzIo')
```

Could you point me in the right direction? Thank you!

**Comment by jaswilli** [comment]
Hi,

I think the answer is going to depend upon what kind of endpoints you're working with. You can query for shared endpoints that you have access to by using the `endpoint_search()` function and passing in the search filter `shared-with-me`.

That will only return "shared" endpoints though. Non-shared or "host" endpoints are different in that in order to access them you have to provide a set of credentials at the time of access. That means that the Globus Transfer API (that's the API you're talking to with the `endpoint_search()` function) isn't able to tell you which of those types of endpoints you might be able to authenticate with.

Does that make sense?

**Comment by vsoch** [comment]
That makes sense, and the use case(s) I am interested in may not fit this model.

## Use Case 1: Openly discoverable data
For example, I may want to create an endpoint / server that has read access (and discoverability) to the world to serve a public dataset.  I would give it some kind of labels or metadata for others to search and find, and link to it from various data science / version control platforms (kaggle, github, etc.). If the endpoint has to be explicitly shared with me or declared, I don't think I can do this. 

## Use Case 2: Template Endpoints
To extend that use case, let's define something called a template endpoint. A template endpoint serves a particular content type and given the content type, has an expected organization. A creator of an application can define a search to return a set of endpoints that match the template, and have confidence the media / data will conform to the template. Anyone can add a new template and it will be discovered.

**Comment by jaswilli** [comment]
> I would give it some kind of labels or metadata for others to search and find

Have you looked at the "keywords" field for endpoints? You can put whatever metadata you'd like in that field and it will be searchable via the fulltext search.

Here's an overview of how searches against endpoint works: https://docs.globus.org/api/transfer/endpoint_search/ -- the overview section lists the data fields which considered for the search query.

**Comment by vsoch** [comment]
Oh fantastic! I will check that out tomorrow and report back. 🤖

**Comment by sirosen** [comment]
👍 to @jaswilli's suggestion: it sounds like you really want to be using the Endpoint Keywords field to filter/control your results.
You should also consider, when you reach the limits of Endpoint Search's capabilities, doing additional filtering on search results which you get back from the API.

An important note about searches, which may not be intuitive: `shared-with-me` filtering does not include publicly accessible endpoints, only ones which are explicitly shared with the current user or one of the user's groups.

I don't think this issue constitutes an action-item against the SDK, and I'm hoping that we've sufficiently answered your questions, so I'm going to close. There's a potential follow-up documentation item that I'll add to our tracking.
