### ISSUE TITLE
Search Client returns generic errors 

### ISSUE THREAD

**Issue by NickolausDS** [globus/globus-sdk-python#275]
The following example fails, given that `index` and `sub` are valid:

```
import globus_sdk
sc = globus_sdk.SearchClient()
sc.get_subject(index, sub)
```

Which results in the following error:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    rec = sc.get_subject(index, sub)
  File "/usr/local/lib/python3.6/site-packages/globus_sdk/search/client.py", line 275, in get_subject
    return self.get(path, params=params)
  File "/usr/local/lib/python3.6/site-packages/globus_sdk/base.py", line 174, in get
    retry_401=retry_401)
  File "/usr/local/lib/python3.6/site-packages/globus_sdk/base.py", line 387, in _request
    raise self.error_class(r)
globus_sdk.exc.SearchAPIError: (400, 'BadRequest.Generic', '/v1/index/frdr-test/subject requires a query parameter "subject"')
```

The offending line is [here](https://github.com/globus/globus-sdk-python/blob/master/globus_sdk/search/client.py#L270), with the [merge_params](https://github.com/globus/globus-sdk-python/blob/master/globus_sdk/base.py#L404) call. The result sets the parameters to `None`, resulting in no data being sent in the request.

**Comment by sirosen** [comment]
Per #274, I misread the patch -- flip-flopping the new and old lines.
Perhaps this was based on a bit of a bias, e.g. I assumed that I would use my own helpers correctly...

Anyway, this is closed via #274
