### ISSUE TITLE
Feature request: Allow passing parameters to oauth2_get_dependent_tokens()

### ISSUE THREAD

**Issue by bjmc** [globus/globus-sdk-python#278]
In the near(-ish) future we'd like clients to pass additional parameters to the dependent token call. For example, specifying `access_type=online` to indicate the client doesn't want or need refresh tokens is supported today. Soon, you'll also be able to pass a `scope` parameter (similar to other OAuth2 calls) to indicate which specific scopes you're interested in receiving dependent tokens for.

**Comment by sirosen** [comment]
Closed by #308
