### ISSUE TITLE
Python Callback for Transfer Completion

### ISSUE THREAD

**Issue by vsoch** [globus/globus-sdk-python#287]
Hey Globus!

Transfer is working in both directions for my application, woohoo! 

![image](https://user-images.githubusercontent.com/814322/38734767-beed62c4-3ef4-11e8-8e89-0140dcc03b7f.png)

We are close to having this finished up! The last component I'm interested in to finish up is what I was reading here about callbacks: http://toolkit.globus.org/toolkit/docs/3.2/developer/globus-async-example2.html

Specifically, is there functionality in the Python SDK (or other) to give the request a callback URL / webhook so that when a transfer is finished, the local server gets a ping that the image is there? (And for your fyi, this means adding it along with it's metadata to the database, which of course we need the image to do properly.) This would be a much simpler and cleaner solution than setting up a task queue to stupidly check for the file at some frequency, so I'm hoping it's possible. If there is also a static endpoint to ping to check if a transfer is done, I could also use this as a backup on something like a server restart if there is chance that the signal was missed. I was inspecting the response object from the transfer api:

```
result=client.transfer_client.submit_transfer(tdata)

In [45]: print(result)
{
  "DATA_TYPE": "transfer_result",
  "code": "Accepted",
  "message": "The transfer has been accepted and a task has been created and queued for execution",
  "request_id": "ki9m6yQWj",
  "resource": "/transfer",
  "submission_id": "7878dcbf-3f18-11e8-ba20-0ac6873fc732",
  "task_id": "7878dcbe-3f18-11e8-ba20-0ac6873fc732",
  "task_link": {
    "DATA_TYPE": "link",
    "href": "task/7878dcbe-3f18-11e8-ba20-0ac6873fc732?format=json",
    "rel": "related",
    "resource": "task",
    "title": "related task"
  }
}
```
and I see the href, and was trying to guess how to use the href and resource, e.g.

 - https://transfer.api.globusonline.org/task/7878dcbe-3f18-11e8-ba20-0ac6873fc732?format=json
 
But at least from the browser, I get resource not found. I'm hoping this second method can be a backup to have a set of "not heard from" urls to check in the local database to parse over given a server restart. The first method of attack would be a notification / webhook we can setup via the python sdk at the onset of the request. 

Thanks again, and happy Friday!

**Comment by jaswilli** [comment]
> I was reading here about callbacks: http://toolkit.globus.org/toolkit/docs/3.2/developer/globus-async-example2.html
> 
> Specifically, is there functionality in the Python SDK (or other) to give the request a callback URL / webhook so that when a transfer is finished, the local server gets a ping that the image is there?

That documentation is for the underlying gridftp software that's running on the endpoints themselves. It would only be useful if you were looking to extend gridftp itself.

The Transfer API doesn't have any sort of async notification mechanism (e.g., webhooks) so your best bet may be polling on the task to check its status. The has a `task_wait` helper that may be useful: https://globus-sdk-python.readthedocs.io/en/stable/clients/transfer/#globus_sdk.TransferClient.task_wait.

Also, to clear up the confusion about using the `href` in the response from the API, it is relative to the Transer API's base URL, which is `https://transfer.api.globus.org/v0.10/` so if you used https://transfer.api.globus.org/v0.10/task/7878dcbe-3f18-11e8-ba20-0ac6873fc732 you would get task data as a response.
