### ISSUE TITLE
Argument order for oauth2_start_flow() differs between NativeApp and ConfidentialApp clients

### ISSUE THREAD

**Issue by bjmc** [globus/globus-sdk-python#290]
I'm not sure if this can be fixed without breaking backwards-compatibility, so maybe not worth caring about. The method signature for `oauth2_start_flow()` differs between the [`ConfidentialAppAuthClient`](https://github.com/globus/globus-sdk-python/blob/master/globus_sdk/auth/client_types/confidential_client.py#L86) and [`NativeAppAuthClient`](https://github.com/globus/globus-sdk-python/blob/master/globus_sdk/auth/client_types/native_client.py#L40)

For confidential clients it's:

```python
    def oauth2_start_flow(
       self, redirect_uri, requested_scopes=None,
       state='_default', refresh_tokens=False):
```

For native app it's:

```python
    def oauth2_start_flow(
        self, requested_scopes=None, redirect_uri=None,
        state='_default', verifier=None, refresh_tokens=False,
        prefill_named_grant=None):
```
Obviously the native app version offers some extra parameters, but it would be very slightly nicer if the first four arguments to both methods were the same, in the same order.

Most people will be writing one or the other type of client, so the only people who could notice and get tripped up by this are users writing both types of clients.

**Comment by jaswilli** [comment]
I would expect most people to be using keyword arguments when calling these functions but who knows I guess.

It would have been nice to catch this on the way in but I'm not sure I can see ever "fixing" it, even on a major version bump, since it could potentially break a lot of code for very little benefit.

Just my opinion, though.

**Comment by sirosen** [comment]
> I'm not sure I can see ever "fixing" it, even on a major version bump, since it could potentially break a lot of code for very little benefit.

I agree. I'm marking as a wontfix.
I just don't see any serious benefit to doing it.

It would have been great to be consistent. But it isn't and it's no big deal. Not worth ruining someone else's day over it, even in v2.
