### ISSUE TITLE
Move testsuite to pytest from nose2?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#291]
This is an unexciting change, but doing it now might free us up for interesting things in the future.
Waiting might result in our tying ourselves more closely to nose2, perhaps accidentally, as tests are added over time.

nose2 has a super-cool core of maintainers. Some of the coolest people ever.
But we acknowledge the growing prevelance of pytest explicitly in the nose2 readme -- there's a lot of momentum behind pytest and nose2 is primarily focused on supporting its existing users, not trying to compete with the growth of pytest.

Given that our testsuite is quite small and not very complex (kudos to us for that), moving to pytest may be wise.
I'm not going to proactively pursue this now, but if someone were to do a rewrite, I'd be very interested in reviewing and potentially accepting it.

**Comment by bjmc** [comment]
Agree that pytest seems to have the momentum behind it.

Are we using anything fancy in the tests that requires either nose2 or pytest? If the test suite stays straightforward and basic, it might be good enough to just write bog-standard `unittest.TestCase` tests, and then the test-runner you choose to execute them becomes more or less irrelevant.

**Comment by sirosen** [comment]
We did the rewrite and also stopped doing calls to live APIs. I'm happy with the results so far, but we'll have to wait and see a bit.

Pytest took a little bit of getting used to, but I like it much better than xunit style tests.
