### ISSUE TITLE
ConfidentialAppAuthClient.oauth2_token_introspect says "identity_set", not "identities_set"

### ISSUE THREAD

**Issue by akkornel** [globus/globus-sdk-python#293]
Hello!

I'd like to report a possible inconsistency in the Globus Python SDK documentation, compared to the Globus Auth API Reference.

I am working on an application, and part of the application's work involves pulling a person's linked identities.  I am using the Python SDK.  I am also using the Confidential Client, because this is something living on a web server (as opposed to JavaScript, or on a user's system).  I am including "urn:globus:auth:scope:auth.globus.org:view_identity_set" in the list of scopes that I request.

In https://docs.globus.org/api/auth/reference/#verifying_identity_via_openid_connect_id_token Section 3.9, I learned that in order to get a person's complete list of identities (including linked identity UUIDs), I need to do a token introspection, including the "identities_set".

But, in https://globus-sdk-python.readthedocs.io/en/stable/clients/auth/#globus_sdk.ConfidentialAppAuthClient.oauth2_token_introspect, I get the impression that I needed to include "identity_set" ('identity', singular).

In my own testing, it seems that the API Reference docs are correct: When I called `oauth2_token_introspect(TOKEN_HERE, include='identity_set')`, I did not get an identities set.  I tested this with a token attached to my own identity, and I have one linked identity, so I expected an identities set with two members.

Please let me know if you need more information.  Thanks very much!

**Comment by mattias-lidman** [comment]
Hello,

I can't speak for the SDK, but the Globus Auth API supports both. `identities_set` is the recommended param, and `identity_set` is supported for backwards compatibility. Note though that you get it back in whatever format you asked for it, so if the request is for `identity_set` the response parameter is also `identity_set` and vice versa.

**Comment by akkornel** [comment]
Oh, interesting!  I did not know that they were both valid.  I guess then that my problem was PEBKAC.  Sorry about that!  But regardless, I do appreciate the additional clarification, and the additional docs content!

**Comment by sirosen** [comment]
> Sorry about that!

Not at all! Thanks for spotting and reporting this.
It's definitely a documentation bug.
