### ISSUE TITLE
Maintenance TODOs

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-sdk-python#323]
* [x] Fix broken license badge in README. (https://github.com/globus/globus-sdk-python/pull/326)
* [ ] Add something in either the README or CONTRIBUTING docs about how to set up project for local development (i.e., `make localdev`).
* [x] 3.8-dev test run failing on Travis. Should be fixed in a future release of pyflakes (flake8): https://github.com/PyCQA/pyflakes/pull/369

**Comment by sirosen** [comment]
Do we feel content with the updates to the contrib doc? Or do you want to add something which explicitly tells you to `make clean test PYTHON_VERSION=python3.6`?

**Comment by jaswilli** [comment]
I think we should have something along the lines of a "getting started" section which could be as simple as letting people know they either should use `make localdev` or will need to `pip install -e '.[development]'` because I don't think that's obvious unless you go digging.

**Comment by sirosen** [comment]
I'll take a crack at a change in the readme.
