### ISSUE TITLE
Require [general] section header in config, be standard INI

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#34]
Although it originally seemed like a nice bit of user-friendliness to not strictly require a section heading for the `[general]` section, it's causing grief in the CLI already ( globus/globus-cli#12 ).

Standard INI format requires that all sections have headers, so we should just move to that.
It does mean that any SDK users will get parsing errors if we do the upgrade harshly.

We should update tokens.globus.org , then tell people on the developer listhost that we're changing this and they should update.
Since the current parser tolerates full INI files, no one will have issues who listens to us.

After that's done, we're still in beta, so I think it will be safe to just drop the special parsing code.

@bda , thoughts?

**Comment by bd4** [comment]
+1

**Comment by sirosen** [comment]
globusonline/tokens#2 is done, so now I think I should notify the dev listhost that we're changing this a bit and then just do it.

@bd4 I'm going to start writing this now, but I have a bit of a question. Should we capture `NoSectionError` and raise a special error message, at least for a short while? I think that would be nice, to see

```
GlobusError("Failed to parse your ~/.globus.cfg Your config file may be in an old format. Please visit https://tokens.globus.org/ to get the latest format of this file.")
```
