### ISSUE TITLE
No attribute 'oauth2_start_flow_native_app'

### ISSUE THREAD

**Issue by sulsj** [globus/globus-sdk-python#348]
Hi, 
Just started testing sdk. I did "pip install globus-sdk" and found v1.7.1 is installed. 
I've got the below while testing the tutorial codes.

Traceback (most recent call last):
  File "get_access_token.py", line 6, in <module>
    client.oauth2_start_flow_native_app()
AttributeError: 'NativeAppAuthClient' object has no attribute 'oauth2_start_flow_native_app'

Any idea?

Thanks,
Seung

**Comment by jaswilli** [comment]
Hi Seung,

The `NativeAppAuthClient` doesn't have that method (as shown by that error). I think it may have existed a long time ago but was renamed at some point. What tutorial are you looking at? It might be outdated and need updating.

If you're looking for some documentation and/or examples the SDK docs can be found [here](https://globus-sdk-python.readthedocs.io/en/stable/), some native app examples [here](https://github.com/globus/native-app-examples). We also have a full example data portal available for reference [here](https://github.com/globus/globus-sample-data-portal).

**Comment by sulsj** [comment]
Hi Jason, 
Oh yes, I figured out the doc is outdated. Thanks for the info.

**Comment by jaswilli** [comment]
Great, glad you got it sorted out. Please let us know if you run into any more questions.
