### ISSUE TITLE
'EELSSpectrum' object has no attribute 'find_peak1D_ohaver'

### ISSUE THREAD

**Issue by xun-zhan** [globus/globus-sdk-python#349]
I was trying to do second derivative of the EEL spectrum, and try to use find_peak1D_ohaver() to locate the first minimum peak position. However, it runs out with the error message above. Could anyone help me solve it? Thanks!

**Comment by sirosen** [comment]
This doesn't appear to be related to the globus-sdk.

It looks like [EELSSpectrum is a HyperSpy class](http://hyperspy.org/hyperspy-doc/current/api/hyperspy._signals.eels.html#hyperspy._signals.eels.EELSSpectrum), so if you have questions about its proper use, you should address them to [the HyperSpy issue tracker](https://github.com/hyperspy/hyperspy/issues).

Though I know nothing about HyperSpy, a quick search finds a method [find_peaks1D_ohaver](http://hyperspy.org/hyperspy-doc/current/api/hyperspy._signals.signal1d.html#hyperspy._signals.signal1d.Signal1D.find_peaks1D_ohaver) in their docs, so this may be a matter of a "peak" vs "peaks" typo.
