### ISSUE TITLE
Feature request: multiple src files transferred to a single dest folder

### ISSUE THREAD

**Issue by jasonsydes** [globus/globus-sdk-python#379]
Hello Globus SDK! Thank you for developing and supporting globus-sdk-python!

I've just spent many hours trying to unsuccessfully perform the equivalent operation with globus-sdk-python:

```scp file1.txt file2.txt file3.txt remote_machine:/some_remote_path/```

Actually, that's not true, I was actually only trying to do this:

```scp file1.txt remote_machine:/some_remote_path/```

But globus-sdk-python kept throwing this error at me:

```globus_sdk.exc.TransferAPIError: (400, 'ClientError.BadRequest', 'The recursive option should be used when transfering directories', 'XKZOhHhpE')```

(If I added "recursive=True", then I would get "NOT_A_DIRECTORY".)

Eventually, I figured out that I needed to do the globus equivalent of the following:

```scp file1.txt remote_machine:/some_remote_path/file1.txt```

This is roughly the bit of code I wrote that actually does it with globus-sdk-python:
```
        tdata.add_item('file1.txt', '/some_remote_path/file1.txt')
        tdata = globus_sdk.TransferData(self.tc, src_ep_id, dest_ep_id, label=label, 
                checksum=checksum, encrypt=encrypt, preserve_timestamp=preserve_timestamp,
                sync_level=sync_level)
```
As someone working with unix variants for over 20 years, this is non-intuitive and frustrating (for example, see cp, mv, scp, rsync, etc, etc, which all follow the patter COMMAND SRC1 [SRC2 [SRC3 ...]] DEST).  Also, it's rather limiting.  It certainly would be better if we could instead do:
```
        tdata.add_item('file1.txt', '/some_remote_path/')
        tdata.add_item('file2.txt', '/some_remote_path/')
        tdata.add_item('file3.txt', '/some_remote_path/')
        tdata = globus_sdk.TransferData(self.tc, src_ep_id, dest_ep_id, label=label, 
                checksum=checksum, encrypt=encrypt, preserve_timestamp=preserve_timestamp,
                sync_level=sync_level)
```
But as it is, we're stuck moving one file at a time.  

(And no, I know I could recursively move the entire directory, but that's exactly what I don't want to do; I want to move two huge files in a directory with a bunch of other huge files that I don't want to move.)

Do you think that's something you could cook up for us?

Thank you again for developing and support globus-sdk-python, it's been very useful to my work!!
Jason Sydes

**Comment by jasonsydes** [comment]
After thinking about it, I suppose it's just a different philosophy, and it's easy enough to code around.  The Globus style just names things the same on both source and destination, whereas the unix style names the destination side as sort of the "bucket" (i.e. a directory) into which you can deposit things from the source side (i.e. files and/or directories).

After sleeping on it, I realize I can code around the Globus style just fine.  So maybe I'm altering my Feature Request to be more of a Documentation Update Request.  It wasn't clear to me from reading the documentation (see [docs here](https://globus-sdk-python.readthedocs.io/en/stable/clients/transfer.html#globus_sdk.TransferData.add_item) or [examples here](https://github.com/globus/globus-jupyter-notebooks/blob/master/SDK.ipynb)) nor from the error messages (e.g. "The recursive option should be used when transfering directories") that the standard "unix-bucket" approach doesn't work in the Globus SDK, and I whittled away probably several hours before it finally clicked.  Maybe that's my shortcoming, but a little extra documentation would have really helped me out there.

Thanks again for all you do!

**Comment by sirosen** [comment]
Sorry I didn't see this when it came in.

I can add a small note to the documentation to clarify this, but I don't think we'll modify the SDK behavior.
We have a long-standing design decision not to try to alter or "zhuzh up" any of the underlying web APIs that the SDK exposes, and the requirement for this format for source and dest paths comes from the Transfer API.

Although it's not something we'd want in the SDK itself, you could write your own special-sauce class for your use-case.
Something like:
```python
class TransferDataCommonDest(TransferData):
    def __init__(self, transfer_client, source_endpoint, destination_endpoint, base_path, **kwargs):
        super().__init__(transfer_client, source_endpoint, destination_endpoint, **kwargs)
        self.destination_base = base_path

    def add_item(self, source_path, **kwargs):
        # NB: won't work right on Windows
        destination_path = os.path.join(self.destination_base, os.path.basename(source_path))
        super().add_item(source_path, destination_path, **kwargs)
```

There's nothing I can do about the error message, but I'll add a note to the docs on globus_sdk.TransferData to state the requirement more clearly.
