### ISSUE TITLE
Add a helper for Task Wait

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#40]
We started talking about the potential merit of having the SDK handle Task Wait itself.

I think the simplest approach is to have a method that times out and returns True/False depending on whether or not the task completed.

Basic signature and behavior I'd like to recommend:
```python
def task_wait(task_id, timeout=10, polling_interval=1):
    """
    Wait until a Task is complete or fails, with a time limit. If the task is "ACTIVE" after time
    runs out, returns ``False``. Otherwise returns ``True``.

    :param uuid task_id: ID of the Task to wait for completion
    :param int timeout: Number of seconds to wait in total. Minimum 1
    :param int polling_interval: Number of seconds between queries to Globus about the
    Task status. Minimum 1
    """
    ...
```

I think it's important to support both a timeout and a polling interval, to let clients make their own decisions about how long to wait and what to do between polling periods.
By way of example, I could see a system working multiple transfers with lax latency requirements wanting to cycle between them in a single thread.

There's a viable approach, for supporting the CLI heartbeats, of adding a generic "polling callback" that gets the results of `get_task(task_id)` every time it's called and is assumed to take 0 seconds.
Consider:

```python
def task_wait(task_id, timeout=10, polling_interval=1, polling_callback=None):
    """
    ...

    :param uuid task_id: ID of the Task to wait for completion
    ...
    :param callable polling_callback: A function which takes a Task document, as
    returned by ``TransferClient.get_task``, as its only argument. Called after each
    Task status check to perform an arbitrary action between checks.

    Note: we assume that ``polling_callback`` takes 0 seconds to run.

    For example, one could use the ``polling_callback`` to print a simple message
    between checks.

    >>> def update_ticker(task_doc):
    >>>     print('.', end='')
    >>> client.task_wait(tid, polling_callback=update_ticker)

    This will print a dot every second, until the task completes or 10 seconds run out.
    """
    ...
```

That example replaces the following messy segment:

```python
>>> retries = 10
>>> counter = 0
>>> done_stat = False
>>> while counter < retries and not done_stat:
...     print('.', end='')
...     done_stat = client.task_wait(tid, timeout=1)
...
......
>>> done_stat
True
```

To me, that ability to inject functionality between the polling calls simplifies things tremendously.
So long as we state that we assume it to take 0 seconds, it doesn't add any code complexity internally either.

**Comment by mattias-lidman** [comment]
How about we make the default`polling_interval` something like 10 seconds? Not sure what's a appropriate, but it seems to me that should be fine for most use cases.

Also, can we add a non-zero limit below which it explodes? Of course, they could still hack it but at least then we're strongly discouraging abusive behavior.

**Comment by sirosen** [comment]
After a bit of chatting about this today, we agreed that the callback is unnecessarily complex -- the CLI can just do its own thing, no need to burden other clients with that.

Additionally, given the current time for starting transfers, there's no sense in having a polling interval under 1 second. (Use cases for this exist, but they are actually highly specialized).
So, we'll go with a default interval of 10s, tune-able down to 1s, and no polling callback.
