### ISSUE TITLE
Add support for 3-Legged OAuth for "Native App" clients to Globus Auth

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#41]
Globus Auth is adding a concept of "Native App" clients which do a full 3-legged OAuth flow even though they do not have a client secret.
Doing this flow requires the use of a temporary PKCE secret to play the role of a client secret when getting an authorization code.

Although support for this flow in the CLI ( globus/globus-cli#16 ) is the first target, we should make sure that our bindings are sufficiently generic that they can be used for applications employing other flows.
In particular, some apps will be using an embedded browser to implement this flow, and supporting that as well as CLI use will probably cover the majority of our use cases.

After a discussion with @jaswilli, we reached the conclusion that there's little use for the state parameter passed through the OAuth flow, so we don't need to contend with the possibility of multiple simultaneous authentication flows. Handling one at a time will be sufficient for the foreseeable future.

@bd4 I think it's desirable for the SDK to encapsulate parts of this flow, as it has to generate a secret, send it, and then send a related secret to exchange the auth code for a token.
It's nice to think of a client for a given service as your way of "talking to" that service, so I think this should be built as a helper hanging off of the `AuthClient` object.

I'm putting together a proposed structure for this, even though the support for it in Globus Auth has not yet been released.

**Comment by bd4** [comment]
+1 that sounds like a reasonable way to support it in the SDK.

**Comment by sirosen** [comment]
I have fairly significant progress on this in a branch, though I can't double-check it against production stacks until somewhat later.

However, one thing that became clear was that it's desirable to call methods on the `AuthClient` while suppressing the builtin logic for handling the Authorization header.
In the case of an end-user making calls, automatically putting an access token in place may be desirable, but for internal usage, having Authorization set by `self.post` and similar calls is in the way.

@bd4 Can you think of a clean way of masking it out / overriding it temporarily? I haven't figured out anything good yet.

**Comment by bd4** [comment]
Maybe add an auth_header kw arg to `_request` and friends, that would override whatever is in `self._headers`? Basically resurrect the deprecated `auth` param but make it support any auth mechanism that only requires setting the `Authorization` header.

Alternatively could try making auth more OO, pass an `Authenticator` instance that either gets to wrap the underlying requests call or gets passed the entire header dict. That seems like overkill though.

**Comment by sirosen** [comment]
So, my only issue with the idea of sending `auth_header=...` is that I really want to say `no_auth_header=True` or equivalent.
When `auth_header` is a truthy/falsey value, normally that would mean passing in something flasey, like `None`.

But `None` here would also be the sensible default meaning "no value from caller", which is totally different.

I agree that the heavy OOP approach seems way overkill.

What do we think of the `None` vs. `False` distinction?
So `auth_header=None` means "no value" but `auth_header=False` means "strip out the Authorization header".

**Comment by bd4** [comment]
I would word it as `auth_header=None` means 'use class default value'. Allowing `False` as well with different meaning is a little hacky, but it is flexible if we really need to allow unique auth mechanism for specific API calls. This might actually be useful in transfer if we wanted to include the new GCS APIs (so far just get cert and get anon acls), but those are in `/private/` namespace so we probably don't went them in the official client. But maybe indicates that it might be useful in the future? I'm not against `no_auth_header=True`, that is tightly scoped to this exact use case.

**Comment by sirosen** [comment]
I actually ended up going with the `no_auth_header` route, as it seems the least disruptive.
Agreed that `None != False` feels hacky, and I think it leads to confusion down the line.
