### ISSUE TITLE
Figure out how to manage multiple access tokens + refresh tokens in Client objects

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#43]
I had a bit of discussion with @jaswilli about this, and it's pretty clear that our thinking to-date about how to manage tokens isn't going to work for more sophisticated use cases, especially as refresh tokens come into play.
We need to design something more complete.
For now, I'm focusing on the model in memory, and assuming that we can figure *something* out to represent it in the config when we're done.

Consider the case of an application that wants to use `TransferClient` to perform a set of operations, and already has a Transfer Access Token + Transfer Refresh Token in hand.

We could do this:

```python
tc = TransferClient(access_token=transfer_access_token)
...
```

However, if the interpreter instance is long-lived or if there's a long delay between getting the access token and this instantiation of the client, we risk having `tc` throw a `TransferAPIError` with code `401` at any time, during any operation, as the token expires.
Even without a long period of time passing, the access token could be invalidated in the middle of an operation.

The catastrophically bad case is that of a paginated call which expires part-way through:
```python
for item in tc.operation_ls(...):
    call_func(item)
```

could throw a `401` any time that the loop ends and triggers `next()` on the `PaginatedResource`.

Even if we tell people that they have to be ready to catch a `401` and refresh, the logic to resume pagination is fairly tricky, and we're losing a lot of the value of the iteration interface.

---

I'm going to enumerate the options I can think of as I think of them.
There are many more than what I'm listing here.

Option 1: Give TransferClient Refresh Tokens, Catch 401s Internally
---

My first thought was to give the `TransferClient` its refresh tokens directly, and have it handle things.
However, this starts to devolve almost immediately:

```python
tc = TransferClient(access_token=transfer_access_token, refresh_token=transfer_refresh_token, auth_client_id=...)
tc.operation_ls(...)
```

`TransferClient` methods are then able to talk to `auth.globus.org` to refresh their tokens whenever they get a `401`.
However, it's very weird that the client consumes an `auth_client_id`.
Without that ID, it's not possible to do the refresh token flow.
It's also a bit aberrant that `TransferClient` is talking to `auth.globus.org` -- that seems like a violation of the `TransferClient` / `AuthClient` separation.

Option 2: Give TransferClient an AuthClient to use, Catch 401s Internally
---

The logical next step is to give `TransferClient` a reference to an `AuthClient` in addition to its tokens.

```python
ac = AuthClient(client_id=...)
tc = TransferClient(access_token=transfer_access_token, refresh_token=transfer_refresh_token, auth_client=ac)
```

Now, if we're inside of a method body, we'd do something like this:

```python
def operation_mkdir(self, endpoint_id, path, **params):
    resource_path = self.qjoin_path("operation/endpoint", endpoint_id, "mkdir")
    json_body = {'DATA_TYPE': 'mkdir', 'path': path}
    try:
        return self.post(resource_path, json_body=json_body, params=params)
     except GlobusTransferAuthRequiredError:
        self.access_token = self.auth_client.refresh(self.refresh_token)
        return self.post(resource_path, json_body=json_body, params=params)
```

This is starting to look promising, but there are a couple of problems:
- What if the request mutates data in addition to returning a `401`?
- Extra network IO when we should really know whether or not the token is about to expire (Auth gives us the `expires_in` field)
- Will handle very poorly in the `PaginatedResource` code, which must now see the `TransferClient` and `AuthClient` to update the access tokens

That first case seems like one we should rule out by just Not Letting APIs Do That.
If we can't make rules about APIs, this is going to get too painful.
A token could be invalidated at any time, so any call can produce errors -- we need to be able to reason about the retry logic in that case.

It would be nice to handle the extra IO load by checking `expires_in`, but that's not always possible.
If we refreshed recently, it should be.
I'd like to bundle that check with the error handling in some way, if possible.

Options 3: BaseClient accepts an AuthClient + Tokens, Check + Refresh Happens in BaseClient._request
---

This looks a little weird because `BaseClient` is a parent of `AuthClient`, but I think it works quite well.

Using Transfer as an example still,
```python
ac = AuthClient(client_id=...)
tc = TransferClient(access_token=transfer_access_token, refresh_token=transfer_refresh_token, auth_client=ac)
```

This is the same as above, but then, rather than having `tc.operation_mkdir` handle the logic, it goes into `BaseClient._request` something like this:

```python
# conditions necessary for a refresh to be at all possible
can_refresh = (self.auth_type == self.AUTHTYPE_TOKEN and
               self.auth_client is not None and self.refresh_token is not None)

if can_refresh:
    # looks up the access token + (nullable) expires_in for the given refresh token
    # refreshes the token if it's near expiry, return the access token
    self.set_token(self.auth_client.refresh(self.refresh_token, check_expiry=True))

r = self._session.request(method=method, url=url, headers=rheaders, params=params,
                          data=text_body, verify=self._verify)

# allow_refresh_and_retry is a kwarg to all request methods, defaults to True
# it is an explicit control on this behavior, for any endpoints where a retry after 401 is considered
# dangerous
if r.status_code == 401 and can_refresh and allow_refresh_and_retry:
    self.set_token(self.auth_client.refresh(self.refresh_token))
    r = self._session.request(method=method, url=url, headers=rheaders, params=params,
                              data=text_body, verify=self._verify)
```

This is not meant to be what we actually write in `BaseClient` -- I've just simplified it a bit to show the kind of thinking I'm engaged in.

The thing I dislike the most is the relationship between `BaseClient` and `AuthClient` that it creates.
There's a bidirectional dependency there, and although no circular imports are being created it's still more complex than I would like.

Another variant on this is to have a `AuthTokenRefreshManager` object, which can be easily synthesized from an `AuthClient` object, and use that in `BaseClient` as well.
It doesn't *really* solve the relationship between a `BaseClient` and an `AuthClient`, but it makes the object model maybe somewhat cleaner.

**Comment by bd4** [comment]
Option 3 sounds the best to me. I think using `AuthClient` directly is best, because the dependency exists and adding an intermediary just obfuscates that.

**Comment by sirosen** [comment]
@bd4 After spending some time fiddling with things and thinking about how to swing all of this, I'm starting to come around to the idea of an object oriented model like the one we discarded in #41 (discussing `no_auth_header`).

Here's the problem that I see: we have at least 4 different ways of generating Authorization headers, at least 3 of which should have the same interface for `BaseClient`.
- No header
- Basic Auth (client credentials)
- Access Token (but no Refresh Token)
- Access Token + Refresh Token to handle expiration (also covers Refresh Token sans Access Token)

Now, not having an Authorization header at all is kinda weird -- I'm not sure that _has_ to be handled the same way as the others.

I did some scribbles this morning, and I was thinking of this:

1. Every `BaseClient` may have a `GlobusAuthorizer` instance attached to it.
2. `BaseClient._request` uses `BaseClient.authorizer.get_authorization_header()` to get an Authorization header
3. Upon seeing a 401, `BaseClient._request` will try `BaseClient.authorizer.missing_authentication_handler(...)` which returns either `GlobusAuthorizer.HANDLER_CODE_ABORT` or `GlobusAuthorizer.HANDLER_CODE_RETRY` and retry once (and only once!) unless we got `no_authorization_retry=True` as an arg to `_request()`

I'm not sure what parameters would be useful/necessary for `missing_authentication_handler`, but I think we should specify that it must accept arbitrary args/kwargs in case someone else wants to implement one and we change the interface a bit in the future.

This covers the various needs nicely because `get_authorization_header()` for each of the auth types has a clear and obvious meaning.
For Basic Auth and a raw Access Token, format a string, and for Access Tokens + Refresh Tokens, you can do a lot of logic there: check `expires_in` if you have it (tracked in the authorizer itself), try the Access Token format string, and handle retries by doing a refresh.

---

Now, pushing this thinking further (don't make fun of me like I'm a Java zealot, this just seems like the right pattern!), we need to talk about the `GlobusAuthorizer` Factories & Builders.

Class constructors are fine for `NullAuthorizer` (if we go that route), `BasicAuthorizer`, and `AccessTokenAuthorizer`.
But a lot of params go into `RefreshTokenAuthorizer` -- and in some cases you've *just* gotten the tokens that you're about to use...

Should `GlobusOAuthTokenResponse` have a method for this?
I'm thinking `GlobusOAuthTokenResponse.build_authorizer(<resource_server_name>)` which does the following:
- If there are only access tokens, gets the correct token for the given resource server and make an `AccessTokenAuthorizer`
- If there are refresh tokens, get the all of the available info (`expires_in` plus the tokens, really) and make a `RefreshTokenAuthorizer`

Final usage would look something like this, to the outside world:

```
ac = AuthClient(client_id=..., client_secret=...) # implicitly creates and attaches a BasicAuthorizer
# do OAuth flow to get token_response
...
tc = TransferClient(authorizer=token_response.build_authorizer('transfer.api.globus.org'))
```

or you could also do

```
tc = TransferClient(token=...) # implicitly makes an AccessTokenAuthorizer
```

or even

```
# omits access token and expires_in -- they'll be found on the initial, automatic refresh
tc = TransferClient(authorizer=RefreshTokenAuthorizer(client_id=..., refresh_token=...))
```

which really is the same as

```
tc = TransferClient(
    authorizer=RefreshTokenAuthorizer(auth_client=AuthClient(client_id=...), refresh_token=...)
```

but we probably don't actually expose that last one in the `RefreshTokenAuthorizer`'s available constructor parameters.

:weary:
There's so much going on here...
I don't want to balloon the SDK complexity, but I think the `GlobusAuthorizer` pattern might be the least-bad path forward.

**Comment by sirosen** [comment]
I've tried out an implementation of the `GlobusAuthorizer` strategy in a branch, [refactor/authorizers](https://github.com/globus/globus-sdk-python/compare/refactor/authorizers).
It's actually not too ugly. Ultimately, some better naming than what I suggested above leads to a much better state of affairs. You can see the results in that branch.

I also ended up giving some attention to our client constructors.

I think it makes sense to allow all of these:
```python
# Basic Auth
ac = AuthClient(client_id=..., client_secret=...)
# Raw AT
ac = AuthClient(access_token=...)
tc = TransferClient(access_token=...)
# Arbitrary
ac = AuthClient(authorizer=...)
tc = TransferClient(authorizer=...)
```

The bigger question is whether or not to allow

```python
# have to bundle them together because (1) they're all required together and (2) naming conflicts
# with existing AuthClient parameters
ac = AuthClient(refresh_credentials=(<refresh_token>, <client_id>, <client_secret>))
tc = TransferClient(refresh_credentials=(<refresh_token>, <client_id>, <client_secret>))
```

which is just a convenient shorthand for

```python
# client_secret can be None here and above, but only on Native App clients
ac = AuthClient(authorizer=RefreshTokenAuthorizer(<refresh_token>, <client_id>, client_secret=...))
tc = TransferClient(authorizer=RefreshTokenAuthorizer(<refresh_token>, <client_id>, client_secret=...))
```

Note that all of this fanciness is not strictly necessary, and bloats the constructors with error checking in which we assert that they didn't give us a combination of ways of authorizing.
(I think such error checking is far superior to some mysterious precedence order among authorization techniques).

However, I think that there's a lot to be said for `AuthClient(client_id=..., client_secret=...)` over `AuthClient(authorizer=BasicAuthorizer(<client_id>, <client_secret>))`.
It's also worth bearing mind that if you plan on using the client to do OAuth2 flows, it will need to embed the client ID in some places, which leads to.... `AuthClient(client_id=<client_id>, authorizer=BasicAuthorizer(<client_id>, <client_secret>))` and then I want to run away screaming. Ick.
Requiring an explicit `authorizer` is easier, but I just think it gets too gross.

**Comment by bd4** [comment]
I think having a `build_authorizer` method in the token response is overkill. Same for having extra syntactic sugar to avoid having to specify the authorizer class. I think if there are examples in the docs, it doesn't matter if it's a bit verbose. I think that's preferable to having multiple syntaxes.

**Comment by sirosen** [comment]
I'm still working through this, on top of the Native App Grant work, which is presumably much less controversial: https://github.com/globus/globus-sdk-python/compare/feature/auth/pkce-exchange

Removing extra syntaxes for handling credentials removes a bunch of noisy logic, so I'm a fan of that.
I'm also (for now at least) supporting the access tokens from config by creating an `AccessTokenAuthorizer` implicitly if none is given.
We can drop that behavior or make it something more interesting later.

The point where things get tricky is the `AuthClient`, which I *think* needs to start to be aware of whether it represents an end user, a native app, or another type of app.
I've started on this using a simple enum of constants, but maybe there's a better way (?).
