### ISSUE TITLE
Attempt to move off of `six`

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#51]
Because `six==1.4.1` is embedded in the OSX system python, we get a conflict with our included version if someone does a `sudo pip install globus-sdk` on OSX. This is also described in #45
The result is that our six is installed behind the system version, and isn't the one loaded at import time.

Solutions that have been batted around include just doing doc about virtualenv ( #45 ), trying to modify `sys.path`, and moving off of `six` altogether.
Although the virtualenv is a best practice, and ultimately the safest solution, it's desirable to let people do the global pip install if we can support it without too much effort.
The push to do that becomes somewhat stronger when you consider that these dependencies are inherited by the CLI.

The current usage sites for `six` are as follows:

- `six.add_metaclass` on base Authorizer
- `six.moves.configparser` in config loading
- `six.moves.urllib.parse` in a couple of locations
- `six.Iterator` as a parent of `PaginatedResource`

The use of `six.moves` is pretty easy to work around, since the things that are renamed generally haven't changed their signatures. Even if they have, we can wrap methods with our own helpers to handle this.
[six.Iterator](https://pythonhosted.org/six/#six.Iterator) is a convenience like the `six.moves` module, so that's also not a big deal.

If we had meaningful things in `six.add_metaclass`, this could get really painful trying to define 2-to-3 compatible metaclasses, but we're just using it to make an abstract base class non-instantiable.
That's not really important -- having all of its methods raise `NotImplementedError` communicates the same thing.

Unless there's a gotcha somewhere in this, we should just go ahead and do it.
This does *not* obsolete #45 -- that's still a best practice and we should encourage it.

**Comment by jaswilli** [comment]
In the case of the the CLI, I get why doing a global (`sudo pip...`) install would be desirable instead of a virtualenv so I think it's worth trying to work around this problem. I feel like telling OS X users to install python from homebrew is totally reasonable and it's a "one and done" solution to this problem.

**Comment by sirosen** [comment]
@jaswilli I think there's an element of this which is just "how seamless can we make this?"
That's presumably the main drive for us being asked to solve this conflict.

I would rather tell people to use a virtualenv than tell them to use homebrew -- though in an ideal world the OSX users would be doing both.
It would be great if we could ask everyone to use homebrew, but I doubt we can get away with it.


The trouble with the CLI use-case is that part of its target audience is totally non-technical.
Excepting a dependency chain like this, there should never be someone installing the SDK who isn't comfortable with a virtualenv -- if there is, that person will have much bigger problems than just getting it up and running.

I spent some time last night looking into build/install software that the CLI could use.
That's a dark, dark place, and it frightens me, but there is [pyinstaller](https://github.com/pyinstaller/pyinstaller)
If we do a binary distribution for the CLI, I think we'd do OSX-only to reduce our testing burden.

I don't like not getting to use this library just because some people might be installing our package in a very bad way, but it's worth noting that a large number of internal people outside of the dev team ran into this when first doing installs of the CLI.
Given the choice between doing a lot more work to support the CLI, or just not using `six`, I think the choice is clear.
Our scariest dependency on `six` that I see is the `six.reraise` we're discussing in globus/globus-cli#26


I don't like any of the paths forward, to be honest, since I feel like OSX is providing the illusion that you have a functional python install, when really you just have permission to sometimes touch the system's python.
I just think this is the least evil approach, given the constraint that asking people to install a copy of the interpreter that they actually own is probably beyond a significant segment of the target audience.

**Comment by jaswilli** [comment]
The problem, as I see it, with jumping through hoops to solve a conflict with system python is that any OS X update could cause a new or recurring issue. For example, OS X (MacOS!) 10.12 is coming next week--who knows what issues that will bring...

For the SDK itself, I don't see any need to push people towards using homebrew, or even providing any specific installation advice. If you're developing software with python you should be following best practices (homebrew, virtualenv, etc.) anyway.

But in the context of the CLI, I think most people are going to want to have it installed globally instead of needing to start a virtualenv every time they want to use it, so in that case, saying "hey, you should install python from homebrew, ignore at your own risk" is totally fine. If someone who is "non-technical" can get themselves to a shell and deal with installing and using the CLI, I think they can certainly handle install python via homebrew.

**Comment by sirosen** [comment]
I agree with pretty much everything that you've said.
I don't like the idea of [actually fighting with OSX about anything](https://cloud.githubusercontent.com/assets/1300022/18593960/5b9b8f44-7c03-11e6-8d90-aaf2e21a8171.gif).
In fact, I would go so far as to say that our _supported_ method of installation is in a virtualenv, our _recommendation_ for global installs is to use homebrew, and that installing with system python on OSX _might_ work.

The question is how we should behave when someone ignores that information and does
`sudo pip install globus-cli`.


My attitude is that it should typically work, incidentally, because we're exercised a very marginal effort to make sure that it does at least well enough for the people using it in-house.
If there are ever significant hoops to jump through, we can rehash our stance regarding MacOS (but only for versions after Mac OS 9 :wink: ).

Does that sound acceptable?

**Comment by jaswilli** [comment]
> The question is how we should behave when someone ignores that information and does
> sudo pip install globus-cli.

"Doing a system-wide install has known issues and we strongly recommend using python installed via Homebrew. Instructions can be found here [link to our quick install instructions in the readme]" is how we handle it I think.

**Comment by sirosen** [comment]
If we actually feel comfortable enforcing that you can't use a stupid python, I think that would  be great.
I'm worried that others will feel very strongly that it should work "out of the box" on OSX regardless of the hurdles.

However, I'm not just trying to represent opinions that I suspect other people have: personally, I would like it to be able to work in that context if it doesn't cost us too much. I think being able to just `sudo pip install globus-cli` and have something work is a better experience than being told to install from homebrew. (Even though it's wrong "in principle" and we tell you not to do it.)

Given how little we're using this package, I don't think the cost is inordinately high right now -- as you pointed out, the main relevant worry is that MacOS will give us more headache down the road.
We shouldn't get caught having committed ourselves to supporting it in that way.

Small aside: I see this as a general compatibility thing too. `six` is so heavily used that I worry, admittedly only a little, about a conflict with someone else's package set in the future.

**Comment by sirosen** [comment]
Worth noting, I think our key point of disagreement is this:

> If someone who is "non-technical" can get themselves to a shell and deal with installing and using the CLI, I think they can certainly handle install python via homebrew.

I don't think homebrew is hard, but I think you underestimate the weirdness of some of our audience.

**Comment by corpulentcoffee** [comment]
Anecdotally, when I had to use OS X (albeit ~3 years ago at a previous job), I found that Homebrew required quite a bit of care and feeding to keep it in a working state (e.g. having to install Xcode components, agreeing to weird EULAs, cryptic error messages, `brew doctor`, major breakages after OS X updates)... I wouldn't want us to have to be supporting the state of people's Homebrew setups too much.

**Comment by corpulentcoffee** [comment]
Closed by globus/globus-cli#41
