### ISSUE TITLE
Token Introspect Doesn't Support "include" parameter

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#64]
I ran into this while trying to use the introspect call.

[Per the docs](https://docs.globus.org/api/auth/reference/#token_introspection_post_v2_oauth2_token_introspect), you have the include the additional parameter: `{'include': 'identities_set'}` to get a full identity set as part of the introspect response.

For now I've got my code using `AuthClient.post` directly, so this is easy enough to work around, but we should add support for that parameter out of the box.
Since that's the only supported value, and that most introspect callers will want it, I would even argue that it should be set by default.

**Comment by bjmc** [comment]
We still need to have some discussions about the availability of that information. I think it's possible that much of the current use of the introspect endpoint would be better served by the [OIDC userinfo endpoint.](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo)

**Comment by mattias-lidman** [comment]
Yes. There's also some unclarity on who should be able to view that information.

**Comment by sirosen** [comment]
Is the plan to drop support for that information coming back with introspect?
From a usage perspective, it's nice to be able to do a single introspect call on every call I receive, and have additional information sideloaded with the `active` status of the token. It's that many fewer calls to wrap in retries, etc.

If there were a userinfo endpoint we could call, it would make less sense for additional information being the default setting for token introspect.

Regarding who can view these things... This goes well beyond the scope of SDK components, but one viable model is to enforce that this information is retrieved through a dependent token. That would be somewhat bothersome to deal with, however.
