### ISSUE TITLE
Missing f-string in parameterized url

### ISSUE THREAD

**Issue by blawney** [globus/globus-sdk-python#682]
When attempting to use the endpoint_manager_task_successful_transfers method, my call failed with 400 (despite providing a valid UUID task_id arg as a string).

https://github.com/globus/globus-sdk-python/blob/main/src/globus_sdk/services/transfer/client.py#L2162

**Comment by sirosen** [comment]
Thanks for reporting this! I'll get this fix in with a test for it right away.

**Comment by sirosen** [comment]
We'll try to get the fix released shortly.

In the meantime you should be able to work around the bug with
```python
transfer_client.get(
    f"endpoint_manager/task/{task_id}/successful_transfers",
)
```

Please let us know if you (a) have trouble with that workaround or (b) spot any other issues!
