### ISSUE TITLE
Add `autopep8` diff to linting validation?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#83]
@jimPruyne recently submitted a PR with what I considered a noisy diff, but it turns out that diff was generated by `autopep8` in his workflow.

We can easily see what would change with an `autopep8` run on the whole repo with `autopep8 -r --diff globus_sdk`
It doesn't look like much to me, and none of the things it changes are things I feel very strongly about (so long as we're consistent, really).

`autopep8` is a good tool and I want to be friendly towards its usage.
Should we do a single run of `autopep8 -r --in-place`, and then add the diff command to Travis?
Or do a single run of it `--in-place` but not enforce it in Travis (which is more accepting, but could lead to noise when someone does run autopep8 on a module)?

@jaswilli, @corpulentcoffee, your feedback would be appreciated.

**Comment by corpulentcoffee** [comment]
I just ran it against the SDK codebase, and everything it did is how I personally write new Python code anyway (e.g. including a space between the class docstring and the first method, moving the closing brace of a dictionary initialization to the block level), so it certainly wouldn't bother me.

**Comment by jaswilli** [comment]
I'm not a fan of auto-formatting tools. If autopep8 is doing something desirable that we're not currently checking via flake8, can we make flake8 enforce it?

**Comment by corpulentcoffee** [comment]
We can get the change autopep8 made to the dictionary closing braces by enabling E123. I don't know if there's an option for the spacing between the class docstring and the first class method.

**Comment by sirosen** [comment]
So, the issue that came up in #82 was actually a matter of `autopep8` enforcing a recommendation of [PEP 257](https://www.python.org/dev/peps/pep-0257/).
It apparently states that a class docstring should be followed by a blank line ([citation](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)).

`flake8` doesn't seem to support PEP257 enforcement.
I tried using the [pep257](https://pypi.python.org/pypi/pep257) linting tool, and... well, it's awful. It complains about all sorts of garbage I just don't consider important, like modules which don't have module-level docstrings.

If we talk about bringing in a second linting tool to pacify `autopep8`, it might as well be `autopep8` in `--diff` mode anyway.

I'm trying to figure out what set of `autopep8` rules would need to be disabled to make things come up clean right now.
I've started with `autopep8 -r --diff globus_sdk --ignore 'E301'`, which makes it skip on the extra lines after docstrings.

**Comment by sirosen** [comment]
We're already pretty close to the strictest enforcement available in flake8.
I'll open a PR to up that the rest of the way -- that's a good practice anyway.

**Comment by sirosen** [comment]
We talked this through a bit and agreed to not add anything using `autopep8`.

If you are using `autopep8` and want to ensure you're submitting a clean diff, you should ensure that you are running `autopep8 --ignore E301,E302,E309` to suppress whitespace changes which are not enforced by `flake8`.
Alternatively, open a PR to fix the whitespace to be compliant with the `autopep8` norms -- we're okay with that, so long as we don't get the whitespace changes embedded in other things.
