### ISSUE TITLE
Add validate_token to AuthClient

### ISSUE THREAD

**Issue by sirosen** [globus/globus-sdk-python#97]
As soon as this is added to the docs site, we should add this to either `AuthClient` or `ConfidentialAppAuthClient`.
We should wait for the docs to be updated so that we can put a proper `External Documentation` section into the docstring.

@mattias-lidman or @bjmc, can you confirm that this does or does not work for Native App clients?
I would assume that, like introspect, it requires an ID and secret.

If this is the superior call for basic validity checking, we should be sure to update the docstring on introspect to recommend using it instead where possible.

**Comment by jaswilli** [comment]
It does work for Native Apps:

```
requests.post('/v2/oauth2/token/validate', dict(client_id=client_id, token=token))
```

**Comment by mattias-lidman** [comment]
Clients shouldn't, in general, be checking and rechecking token validity. It's up to the RS to determine validity.

That call probably should require authentication, to conform to other policies we have.

**Comment by jaswilli** [comment]
@mattias-lidman We use it in the web app so it can't require authentication.

**Comment by mattias-lidman** [comment]
Yeah, I remember we added it as a alternative to introspect. Why do you actually need it? What need does it fulfill that can't be filled by just calling one of the services you have tokens for?

**Comment by mattias-lidman** [comment]
This might be a more appropriate conversation for Slack...

**Comment by sirosen** [comment]
The Slack discussion seemed a little bit inconclusive. Bumping this back up into the public realm.

> Clients shouldn't, in general, be checking and rechecking token validity. It's up to the RS to determine validity.

That's fine, and probably means that we shouldn't be redirecting people from one call to the other.
It also means that we should ensure that the docs are clear about what and who this call is for.

We could delineate this with another class of `AuthClient`, but that seems like overkill.
Just documentation for now? That seems consistent with our general goal of conservative design in the SDK.

**Comment by sirosen** [comment]
Per globus/globus-cli#153 , there's a use case for this on Native App clients. It should therefore be defined on the base `AuthClient` and have its implementation overridden on the Native App client (to send `client_id` in the body).

Documentation can focus on resource server authors and mention that pure clients generally don't want to use it.
